<?php

namespace MyPoll\Tests\Unit\Classes;

use DI\Container;
use Mockery as m;
use MyPoll\Classes\Database\RedBeanDB;
use MyPoll\Classes\Pagination;
use MyPoll\Classes\Questions;
use MyPoll\Classes\Settings;
use Twig_Environment;
use PHPUnit_Framework_TestCase;

class QuestionsTest extends PHPUnit_Framework_TestCase
{

    protected $dataArray = array('question' => 'question', 'answers' => array('answer1', 'answer2', 'answer3'));
    /**
     * @var Container
     */
    private $container;

    public function setUp()
    {
        parent::setUp();
        global  $container;
        $this->container = $container;
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    /**
     * @param $extraArray array
     *
     * @return RedBeanDB
     */
    private function getMockObject($extraArray = null)
    {
        $database = m::mock('MyPoll\Classes\Database\RedBeanDB');
        if ($extraArray) {
            foreach ($extraArray as $item) {
                $database->shouldReceive($item['method'])->once()->withAnyArgs()->andReturn($item['return']);
            }
        }
        return $database;
    }

    private function getMockData()
    {
        return array(
            'id' => 1,
            'email' => 'email@d.com',
            'user_name' => 'user',
            'user_pass' => password_hash('password', PASSWORD_DEFAULT)
        );
    }

    /**
     * @param $extraArray array
     *
     * @return Questions
     */
    private function getQuestion($extraArray = null)
    {
        $questions =  new Questions(
            $this->getMockObject($extraArray),
            $this->container->get(Twig_Environment::class),
            $this->container->get(Pagination::class),
            $this->container->get(Settings::class)
        );

        return $questions;
    }

    /**
     * @expectedException \Twig_Error_Loader
     */
    public function testAddFail()
    {
        $this->getQuestion()->add();
    }

    public function testGetPostParamsForAddMethodSuccess()
    {
        $_POST['question'] = 'question1111';
        $_POST['answer'] = array('answer1', 'answer2', 'answer3');
        $this->assertEquals(
            array('question' => $_POST['question'], 'answers' => $_POST['answer']),
            $this->getQuestion()->getPostParamsForAddMethod()
        );
    }

    /**
     * @expectedException \PHPUnit_Framework_Error_Notice
     */
    public function testGetPostParamsForAddMethodFailWithNoPostParams()
    {
        $this->getQuestion()->getPostParamsForAddMethod();
    }

    public function testGetPostParamsForAddMethodFailWithEmptyPostParams()
    {
        $_POST['question'] = '';
        $_POST['answer'] = array();
        $this->assertArrayHasKey('question', $this->getQuestion()->getPostParamsForAddMethod());
        $this->assertArrayHasKey('answers', $this->getQuestion()->getPostParamsForAddMethod());
    }

    public function testAddExecuteSuccess()
    {
        $extraArray = array(
            array('method' => 'addRows', 'return' => true),
            array('method' => 'store', 'return' => true),
            array('method' => 'getID', 'return' => true)
        );

        $question = $this->getQuestion($extraArray);
        $this->assertEquals(var_dump($question->addExecute($this->dataArray)), $question->addExecute($this->dataArray));
    }

}
